# Generated by Django 5.0.1 on 2024-01-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="Image"
            ),
        ),
    ]
