# Generated by Django 5.0.1 on 2024-01-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_content_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="section",
            field=models.CharField(
                choices=[
                    ("INTRO", "Introduction"),
                    ("SUP", "Superposition"),
                    ("QUB", "Qubits"),
                    ("MEA", "Measurement"),
                    ("CIR", "Circuit"),
                    ("ENT", "Entanglement"),
                    ("NOI", "Noise"),
                    ("CON", "Control"),
                    ("PRO", "Programming"),
                ],
                default="INTRO",
                max_length=5,
            ),
        ),
    ]
