# Generated by Django 5.0.1 on 2024-01-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="sections/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="sections/"),
        ),
    ]
