# Generated by Django 5.0.1 on 2024-01-12 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_content_image_alter_section_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserContentProgress",
            new_name="UserProgress",
        ),
    ]
