# Generated by Django 5.0.1 on 2024-01-12 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_rename_usercontentprogress_userprogress"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userprogress",
            unique_together=set(),
        ),
    ]
